apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
{{ toYaml .Values.prometheusRules.groups | indent 4 }}