apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-receiver
  template:
    metadata:
      labels:
        app: webhook-receiver
    spec:
      containers:
        - name: echo
          image: mendhak/http-https-echo:42
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver
  namespace: monitoring
spec:
  selector:
    app: webhook-receiver
  ports:
    - port: 8080
      targetPort: http